### ISSUE TITLE
navigatorKey is null when starting app

### ISSUE THREAD

**Issue by filly82** [sermetk/flutterboilerplate#1]
great boilerplate, thanks for that

but unfortunately when starting the app in offline mode then the following error occurs.

`Caught error: NoSuchMethodError: The method 'pushNamed' was called on null.`

I think this is because navigatorKey is null because MaterialApp has not been called yet.
when switching online/offline in an already started app everything works fine

any idea?

**Comment by sermetk** [comment]
Thanks for your interest. I added a generic error alert for offline requests. It should have fixed in the last commit.
